; ================================================================
;  AMR1 — PlatformIO multi-environment
;  Seleccionar el entorno desde la barra de PlatformIO en VS Code
; ================================================================

[common]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = adafruit_feather_can
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit MCP2515
    adafruit/Adafruit BusIO

; ----------------------------------------------------------------
;  TREN MOTRIZ
; ----------------------------------------------------------------
[env:tren_motriz_can]
extends = common
build_src_filter = +<tren_motriz/can/>

[env:tren_motriz_serial]
extends = common
build_src_filter = +<tren_motriz/serial/>

; ----------------------------------------------------------------
;  FRENO
; ----------------------------------------------------------------
[env:freno_can]
extends = common
build_src_filter = +<freno/can/>

[env:freno_serial]
extends = common
build_src_filter = +<freno/serial/>

; ----------------------------------------------------------------
;  DIRECCIÓN
; ----------------------------------------------------------------
[env:direccion_can]
extends = common
build_src_filter = +<direccion/can/>

[env:direccion_serial]
extends = common
build_src_filter = +<direccion/serial/>

; ----------------------------------------------------------------
;  INTÉRPRETE
; ----------------------------------------------------------------
[env:interprete_can]
extends = common
build_src_filter = +<interprete/can/>

[env:interprete_serial]
extends = common
build_src_filter = +<interprete/serial/>
